<?php
/**
 * Страница "Содержание".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью виджета информационной панели (Dashboard).
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Виджет "Лицензия"</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>Виджет <a href="<?= $url('index', 'module:gm.be.license') ?>">информационной панели (дашборд)</a> отображает информацию о лицензионном ключе редакции веб-приложения.</p>
</article>