<?php
/**
 * Страница "Содержание".
 * 
 * Локализации по умолчанию.
 * 
 * Этот файл является частью виджета информационной панели (Dashboard).
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Widget "License"</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>Widget <a href="<?= $url('index', 'module:gm.be.license') ?>">information panel (dashboard)</a> displays information about the license key of the web application edition.</p>
</article>